# Github Action for Deploy of the Firebase Functions

name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  pre_deploy:
    name: Pre Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
  build_deploy:
    name: Build & Deploy
    needs: pre_deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Remove Git folders from distribution
        run: rm -rf .git*
      - name: Install Dependencies
        run: npm install --prefix functions
      - name: Make envfile
        run: |
          touch functions/.env
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: .
  post_deploy:
    name: Post Deploy
    needs: build_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Start Clear artifact
        run: touch artifact-removed
      - name: Clear artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: artifact-removed
